# 传统数据结构的运算

- Python先天内置比较多的数据结构：
    - 元组（tuple）
    - 列表（list）
    - 字典（dict）
    - 集合（set）
    - 不变集合（frozenset）
    
- Python还提供了两个数据类型（也是数据结构）
    - complex
    - range
    
- 争对这些数据结构，还提供了一些全局函数，用来处理这些数据
    - 基本计算：abs，divmod，min，max，any，all，pow，round
    - 排序：sorted，reversed
    - 容器遍历有关：enumerate，iter，next，len，
    - 容器操作：filter，map，zip

## comple类型

- 与int，float，bool，str等一样，用来表示一种数据类型：复数类型

- 复数的字面值表示：
    - 实部 + 虚部
    - 虚部表示：J或者j后缀。
    - 例子：`2 + 4j`，`2.5 - 7.8J`

### 通用运算

In [88]:
cp1 = 3.5 + 7.2J
cp2 = 3 + 3.5j

print(cp1 + cp2)
print(cp1 - cp2)
print(cp1 * cp2)
print(cp1 / cp2)
# print(cp1 // cp2)  # 不支持
print(cp1 ** cp2)

# print(cp1 < cp2)    # 不支持
# print(cp1 <= cp2)
print(cp1 == cp2)
print(cp1 != cp2)
# print(cp1 > cp2)
# print(cp1 >= cp2)

print(+ cp1 )
print(- cp2)

# print(cp1 >> 2)
# print(cp1 << 2)

if cp1:
    print('逻辑判定')
    
print(cp1.conjugate())   # 共轭复数

(6.5+10.7j)
(0.5+3.7j)
(-14.7+33.85j)
(1.68+0.4399999999999999j)
(-3.608319137330337-9.583259554669224j)
False
True
(3.5+7.2j)
(-3-3.5j)
逻辑判定
(3.5-7.2j)


## range类型

In [89]:
rg = range(0, 10, 2)
print(rg.count(1))
print(rg.index(6))

0
3


## 枚举

- enumerate 类型，用于枚举容器元素, 与迭代器的最大区别，是指定开始位置，并返回每个元素的索引位置。
    - 构造器： `enumerate(iterable[, start]) -> iterator`  返回迭代器
    - 运算：
        - `__iter__(self, /)`
        - `__iter__(self, /)`


In [90]:
lt = [1,2,3,4,5]

en = enumerate(lt, 2)
for val , idx in en:    # 索引在后面，值在前面
    print(idx, ':',  val)

    


1 : 2
2 : 3
3 : 4
4 : 5
5 : 6


## filter函数

- filter本质也是一个类型：可迭代类型。用来对数据进行过滤，产生新的数据迭代。

In [91]:
lt = [1,2,3,4,5,0]

ft = filter (lambda x : True if x % 2 ==0 else False, lt)
print(list(ft))

ft = filter (None, lt)   # 第一个参数可以为None，None就表示值为False被过滤
print(list(ft))

[2, 4, 0]
[1, 2, 3, 4, 5]


## map函数

- map函数也是一个特殊的可迭代类型，用于把多个可迭代容器，合并成一个可迭代容器。

In [92]:
lt1 = [1,2,3,4,5,0]
lt2 = [1.2, 2.5, 6.5, 10]

def map_fun(*d):
    #  print(*d)
    sum = 0
    for i in d:
        sum += i
    return sum

mp = map(map_fun,  lt1, lt2)    # 第一个参数不能为None
print(list(mp))

[2.2, 4.5, 9.5, 14]


## zip函数

- zip与map类型差不多，只是map提供一个函数计算，zip是直接把多个可迭代类型，合并成一个元组。

In [93]:
lt1 = [1,2,3,4,5,0]
lt2 = [1.2, 2.5, 6.5, 10]

zp = zip(lt1, lt2)    # 第一个参数不能为None
print(list(zp))

[(1, 1.2), (2, 2.5), (3, 6.5), (4, 10)]


# 数学计算

- Python有一个基因就是计算语言（与R语言，Matlab并称三大计算语言），在标准库中也提供丰富的数学计算与数据处理。

## numbers模块

- 定义一组抽象类，提供给用户来扩展运算符与其他功能。
    - 扩展实现自己的数值类型，麻烦点，这里不演示。

- 内置的类型也遵循这个规范
    - 复数：
        - real
        - imag
        - conjugate()
    - 实数：
        - 提供实数相关的运算，比如除法
    - 有理数：
        - numerator   ：分子
        - denominator ：分母
    - 整数：
        - 提供整数运算：比如位运算。
    

In [94]:
a = 20    # 请变换各种类型，观察下面的运算结果
if isinstance(a,  numbers.Number):
    print('数值类型')
    
if isinstance(a,  numbers.Complex):
    print('复数类型')
    print(a.real, a.imag)

if isinstance(a,  numbers.Real):
    print('实数类型')
    print(a // 2.0)

if isinstance(a,  numbers.Rational):
    print('有理数类型')
    print(a.numerator, a.denominator)
    
if isinstance(a,  numbers.Integral):
    print('自然数类型')
    print(a >> 1)

NameError: name 'numbers' is not defined

## decimal模块

- decimal模块提供精度更高的计算，这个对某些精度有要求的算法是需要的，尽管我们可能在大部分情况下没有这个需求。
    - 提供数值不动点与浮点运算
    - 提供数值计算的上下文。

###  数值计算上下文

- decimal.getcontext()
    - 获取激活线程的当前上下文。

- decimal.setcontext(c)
    - 设置当前线程的上下文。

- decimal.localcontext(ctx=None)
    - 设置当前线程的上下文管理器（`__enter__与__exit__`），并返回原来的上下文管理器。如果ctx=None，则不设置当前上下文，并返回当前下文管理。
        - `__enter__`返回Context对象
        - `__exit__`回复原来上下文。
    - 上下文管理的好处，就是临时使用某个上下文，使用完毕就恢复成原来的上下文。
    

In [95]:
import decimal

ctx = decimal.localcontext()
print(ctx)
ctx = decimal.getcontext()
print(ctx)

Context(prec=28, rounding=ROUND_HALF_EVEN, Emin=-999999, Emax=999999, capitals=1, clamp=0, flags=[], traps=[InvalidOperation, DivisionByZero, Overflow])


### 理解上下文类Context

- flags与traps用来设置Signals.如果新的Context，一般设置traps，不设置flags。flags用来设置记录遇见的Signal条件,每次计算完通过检查flags来确定哪些条件发生，一般在计算完成后都清除掉，这样下次计算的记录才会准确。
    - class decimal.DecimalException ：下面几个类的父类
    - class decimal.Clamped：科学记数法的e指数计算公式是否去除精度
    - class decimal.DivisionByZero：被0除
    - class decimal.Inexact：是否四舍五入
    - class decimal.InvalidOperation：非法操作：对无穷进行计算
    - class decimal.Overflow
    - class decimal.Rounded
    - class decimal.Subnormal
    - class decimal.Underflow
    - class decimal.FloatOperation

- rounding指定四舍五入方式
    - decimal.ROUND_CEILING
        - Round towards Infinity.

    - decimal.ROUND_DOWN
        - Round towards zero.

    - decimal.ROUND_FLOOR
        - Round towards -Infinity.

    - decimal.ROUND_HALF_DOWN
        - Round to nearest with ties going towards zero.

    - decimal.ROUND_HALF_EVEN
        - Round to nearest with ties going to nearest even integer.

    - decimal.ROUND_HALF_UP
        - Round to nearest with ties going away from zero.

    - decimal.ROUND_UP
        - Round away from zero.

    - decimal.ROUND_05UP
        - Round away from zero if last digit after rounding towards zero would have been 0 or 5; otherwise round towards zero.



- 常量设置


常量|32-bit|64-bit|说明
-|-|-|-
decimal.MAX_PREC|425000000|999999999999999999|最大精度: \[1, MAX_PREC\]
decimal.MAX_EMAX|425000000|999999999999999999|指数的最大值：\[0, MAX_EMAX\]
decimal.MIN_EMIN|-425000000|-999999999999999999|指数最小值：\[MIN_EMIN, 0\]
decimal.MIN_ETINY|-849999999|-1999999999999999997|等于MIN_EMIN - MAX_PREC + 1，就是Etiny函数返回的最小值。

In [96]:
import decimal
ctx = decimal.getcontext()
print(ctx.flags)
print(ctx.traps)    # 陷阱
print(ctx.capitals)   # 科学记数法的e是否大小写
print(ctx.clamp)    # 科学记数法的指数精度表示：Emin - prec + 1 <= e <= Emax - prec + 1
print(ctx.Emax)
print(ctx.Emin)
print(ctx.prec)
print(ctx.rounding)


{<class 'decimal.InvalidOperation'>:False, <class 'decimal.FloatOperation'>:False, <class 'decimal.DivisionByZero'>:False, <class 'decimal.Overflow'>:False, <class 'decimal.Underflow'>:False, <class 'decimal.Subnormal'>:False, <class 'decimal.Inexact'>:False, <class 'decimal.Rounded'>:False, <class 'decimal.Clamped'>:False}
{<class 'decimal.InvalidOperation'>:True, <class 'decimal.FloatOperation'>:False, <class 'decimal.DivisionByZero'>:True, <class 'decimal.Overflow'>:True, <class 'decimal.Underflow'>:False, <class 'decimal.Subnormal'>:False, <class 'decimal.Inexact'>:False, <class 'decimal.Rounded'>:False, <class 'decimal.Clamped'>:False}
1
0
999999
-999999
28
ROUND_HALF_EVEN


### 理解上下文管理器

In [97]:
with decimal.localcontext() as ctx:
    print(ctx.flags)
    print(ctx.traps)    # 陷阱
    print(ctx.capitals)   # 科学记数法的e是否大小写
    print(ctx.clamp)    # 科学记数法的指数精度表示：Emin - prec + 1 <= e <= Emax - prec + 1
    print(ctx.Emax)
    print(ctx.Emin)
    print(ctx.prec)
    print(ctx.rounding)

{<class 'decimal.InvalidOperation'>:False, <class 'decimal.FloatOperation'>:False, <class 'decimal.DivisionByZero'>:False, <class 'decimal.Overflow'>:False, <class 'decimal.Underflow'>:False, <class 'decimal.Subnormal'>:False, <class 'decimal.Inexact'>:False, <class 'decimal.Rounded'>:False, <class 'decimal.Clamped'>:False}
{<class 'decimal.InvalidOperation'>:True, <class 'decimal.FloatOperation'>:False, <class 'decimal.DivisionByZero'>:True, <class 'decimal.Overflow'>:True, <class 'decimal.Underflow'>:False, <class 'decimal.Subnormal'>:False, <class 'decimal.Inexact'>:False, <class 'decimal.Rounded'>:False, <class 'decimal.Clamped'>:False}
1
0
999999
-999999
28
ROUND_HALF_EVEN


### 使用上下文

In [98]:
import decimal
ctx = decimal.Context(
    prec=4, 
    rounding=decimal.ROUND_HALF_EVEN, 
    Emin=None, 
    Emax=None, 
    capitals=0,      # 这个参数设置没有什么效果，大小写都可以使用
    clamp=None, 
    flags=None, 
    traps=None)

print(ctx.create_decimal('12.1234567890987654321'))
print(ctx.create_decimal('12.1231e5'))

12.12
1.212E+6


In [99]:
import decimal
f1 = 12.1234567890987654321
f2 = 12.1234567890987654321
print(f1 + f2)


ctx = decimal.getcontext()
ctx.prec = 20   # 改变这个数值看看上下文的影响

d1 = decimal.Decimal('12.1234567890987654321')
d2 = decimal.Decimal('12.1234567890987654321')
print(d1 + d2)


24.246913578197532
24.246913578197530864


### 使用上下文管理器

In [100]:
import decimal
f1 = 12.1234567890987654321
f2 = 12.1234567890987654321
print(f1 + f2)


ctx = decimal.getcontext()
ctx.prec = 20   # 改变这个数值看看上下文的影响

d1 = decimal.Decimal('12.1234567890987654321')
d2 = decimal.Decimal('12.1234567890987654321')

print('外部计算', d1 + d2)

with decimal.localcontext() as tx:
    tx.prec = 4
    print('内部计算', d1 + d2)


print('外部计算', d1 + d2)

24.246913578197532
外部计算 24.246913578197530864
内部计算 24.25
外部计算 24.246913578197530864


## fractions模块

- Fraction类：
    - 提供有理数管理
        - class fractions.Fraction(numerator=0, denominator=1)
        - class fractions.Fraction(other_fraction)
        - class fractions.Fraction(float)
        - class fractions.Fraction(decimal)
        - class fractions.Fraction(string)
    - 可以获取分子分母
        - numerator
        - denominator
- 返回最大公约数
    - fractions.gcd(a, b)  # 这个函数已经在math中实现，这里已经不推荐使用。

In [101]:
import fractions
import math

# print(fractions.gcd(111,22))   # 推荐使用了
print(math.gcd(1111,22))

fr = fractions.Fraction(0.75)
print(fr.numerator, fr.denominator)


11
3 4


## math模块

### 数学常量

- math.pi
- math.e
- math.tau ： $2 * \pi  = \tau $ 
- math.inf
- math.nan


### 数值基本表示计算

In [102]:
import math

r = math.frexp(10)   # 浮点数的内部表示，用于解决不同平台之间浮点数表示的差异的问题
print(r)

print(math.modf(10.25))
print(math.trunc(10.25))   # 阶段

(0.625, 4)
(0.25, 10.0)
10


### 指数与对数运算

In [103]:
import math

print(math.log2(10))

3.321928094887362


### 三角函数

In [104]:
import math

print(math.hypot(4, 3))   # 欧式距离，坐标到远点的距离

5.0


###  双曲函数


- $sinh(x) = \dfrac{e^x - e^{-x}}{2} $


- $cosh(x) = \dfrac{e^x + e^{-x}}{2}$


- $tanh(x) = \dfrac{sinh(x)}{cosh(x)}$


- $coth(x) = \dfrac{1}{tanh(x)}$


- $asin(x) = ln(x + \sqrt{(x^2 +1)} )$  是sinh的反（可逆）函数。

In [105]:
import math

print(math.sinh(1.7))

2.6456319338372323


### 角度与弧度转换

In [106]:
import math

print(math.degrees(math.pi))

180.0


### 特殊数学计算

- 误差函数：就是高斯函数的不定积分

    - 高斯函数： $f(x) = \dfrac{1}{\sigma \sqrt{2 \pi}}\exp ^{\frac{1}{2} {(\frac{x- \mu}{\sigma})}^2} $
    
    - 标准高斯函数：$f(x) = \dfrac{1}{\sqrt{2 \pi}}\exp ^{\frac{x^2}{2}} $ 
    


- 误差函数：
    - $f(x) = \dfrac{1}{\sqrt{2 \pi}} \int_{-x} ^x {\exp ^{\dfrac{t^2}{2}}} dt$ 

In [107]:
import math

print(math.erf(0.5))

0.5204998778130465


## random模块

### seed随机种

- random.seed(a=None, version=2)
    - a=None：一般使用当前时间

In [108]:
import random
print(random.seed())

# print(random.getstate())

None


### 随机整数

- random.randrange(stop)
- random.randrange(start, stop\[, step\])
    - 从`range(start, stop, step)`种随机挑选一个
- random.randint(a, b)

In [109]:
import random
print(random.randrange(10))
print(random.randrange(0, 10, 1))
print(random.randint(1, 10))

0
4
10


### 基于随机分布的随机小数
- random.random()
- random.uniform(a, b)
- random.triangular(low, high, mode)
- random.betavariate(alpha, beta)
- random.expovariate(lambd)
- random.gammavariate(alpha, beta)
- random.gauss(mu, sigma)
- random.lognormvariate(mu, sigma)
- random.normalvariate(mu, sigma)
- random.vonmisesvariate(mu, kappa)
- random.paretovariate(alpha)
- random.weibullvariate(alpha, beta)

In [110]:
import math

random.seed()
print(random.random())
print(random.uniform(0, 1))

0.4105116468739579
0.0034572920379813965


### 随机序列
- random.choice(seq)
- random.choices(population, weights=None, *, cum_weights=None, k=1)

- random.shuffle(x\[, random\])
- random.sample(population, k)

In [111]:
import math

lst = [1,2,3,4,5,6]
print(random.choice(lst))
print(random.choices(lst, weights=[1, 1, 1, 1, 1, 1], k=10))  # 权重的长度必须匹配序列的长度，k可以是任意长

1
[5, 2, 2, 1, 2, 4, 4, 5, 1, 6]


### 系统随机数

- class random.SystemRandom(\[seed\])

In [112]:
import math
"""
'betavariate', 'choice', 'choices', 'expovariate', 'gammavariate', 'gauss', 'gauss_next', 'getrandbits', 'getstate', 'lognormvariate', 'normalvariate', 'paretovariate', 'randint', 'random', 'randrange', 'sample', 'seed', 'setstate', 'shuffle', 'triangular', 'uniform', 'vonmisesvariate', 'weibullvariate']
"""
rs = random.SystemRandom()
print(rs.randrange(10))

0


## statistics模块

### 均值与中值计算



函数|函数功能
-|-
mean()	|Arithmetic mean (“average”) of data.
harmonic_mean()	|调和均值.
median()	|Median (middle value) of data.
median_low()	|Low median of data.
median_high()	|High median of data.
median_grouped()	|Median, or 50th percentile, of grouped data.
mode()	|Mode (most common value) of discrete data.


In [113]:
import statistics
lst = [2, 5, 6, 3, 5, 1, 2, 5, 3, 5]
print(sorted(lst))
print(statistics.mean(lst))
print(statistics.harmonic_mean(lst))
print(statistics.median(lst))    # 中间两个数的均值
print(statistics.median_low(lst))
print(statistics.median_high(lst))
print(statistics.mode(lst))    # 出现次数最多的



[1, 2, 2, 3, 3, 5, 5, 5, 5, 6]
3.7
2.7522935779816513
4.0
3
5
5


### 方差计算


函数|函数功能
-|-
pstdev()	|Population standard deviation of data.总体标准差
pvariance()	|Population variance of data.总体方差
stdev()	|Sample standard deviation of data.样本标准差
variance()	|Sample variance of data.样本方差

In [114]:
import statistics
import math

lst = [2, 5, 6, 3, 5, 1, 2, 5, 3, 5]

print(statistics.pstdev(lst))
print(statistics.pvariance(lst))
print(statistics.stdev(lst)*math.sqrt((len(lst)-1)/len(lst)))   # 屏风跟
print(statistics.variance(lst))
print(statistics.variance(lst)*(len(lst)-1)/len(lst))     # = .pvariance(lst)

1.6155494421403511
2.61
1.6155494421403511
2.9
2.61


# numpy数据结构与运算

## 创建numpy数组

### 使用构造器构造ndarray数组

####  构造器定义：
- `ndarray(shape, dtype=float, buffer=None, offset=0, strides=None, order=None)`
    - shape：数组的形状
    - dtype：数组元素的类型
    - buffer：构造数组的缓冲
    - offset：数组使用的数据在缓冲中的开始位置
    - strides：选取元素的步长
    - order：构造数组的方式（C方式，还是Fortran方式：就是行优先，还是列优先）与strides参数冲突。

#### 使用缓冲构造数组

- 其中order与strides冲突。指定strides后，order就不使用。
- order指定'C'：行优先，'F'：列优先
- strides的单位是字节，不是位。
- buffer需要字节流

In [115]:
import numpy as np

lst = (1, 2, 3, 4, 5, 6, 7, 8, 9)
bts = bytes(lst)

na = np.ndarray(shape=(3, 3),  dtype=np.int8, buffer=bts, offset=0, strides=(2, 1) )
print(na)
na = np.ndarray(shape=(3, 3),  dtype=np.int8, buffer=bts, offset=0, order='F')
print(na)

[[1 2 3]
 [3 4 5]
 [5 6 7]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


#### 不使用缓冲构造数组
- 不使用缓冲，只需要指定dtype与shape即可,构造的数组初始化值是不确定的。

In [116]:
import numpy as np

na = np.ndarray(shape=(3, 3), dtype=np.float32)
print(na)

[[2.3693561e-38 2.3694275e-38 2.3694278e-38]
 [2.3694278e-38 2.3694278e-38 2.3694278e-38]
 [2.3694278e-38 2.3694278e-38 9.2195630e-41]]


### ndarray中可以指定的类型

- ndarray指定的数据类型是numpy.dtype类型,构造器定义如下：
    - `dtype(obj, align=False, copy=False)`
    
    - 其中obj可以使用复合数据（在后面会使用到）。
    
- 该类型有几个关键数据
    -  byteorder
    - itemsize
    - name
    - type
    - str
- 如果ndarray不指定dtype，缺省类型是：float_（就是float64）

In [117]:
import numpy as np

na = np.ndarray(shape=(3, 3))
dt = na.dtype
print('dt.type:', dt.type)
print('dt.byteorder:', dt.byteorder)
print('dt.itemsize:', dt.itemsize)
print('dt.name:', dt.name)
print('dt.str:', dt.str)

dt.type: <class 'numpy.float64'>
dt.byteorder: =
dt.itemsize: 8
dt.name: float64
dt.str: <f8


#### 使用numpy内置标量类型构造dtype

- numpy标准的内置内型：



1. bool类型

Type	|Remarks	|Character code
-|-|-
bool_	|compatible: Python bool	|'?'
bool8	|8 bits	 | 



2. 整数类型


类型|说明|表示字符
-|-|-
byte	|compatible: C char	|'b'
short	|compatible: C short	|'h'
intc	|compatible: C int	|'i'
int_	|compatible: Python int	|'l'
longlong	|compatible: C long long	|'q'
intp	|large enough to fit a pointer	|'p'
int8	|8 bits	 |
int16	|16 bits|	 
int32	|32 bits|	 
int64	|64 bits|	 


3. 无符号整数类型

类型|说明|表示字符
-|-|-
ubyte	|compatible: C unsigned char	|'B'
ushort	|compatible: C unsigned short	|'H'
uintc	|compatible: C unsigned int	|'I'
uint	|compatible: Python int	|'L'
ulonglong	c|ompatible: C long long	|'Q'
uintp	|large enough to fit a pointer	|'P'
uint8	|8 bits	| 
uint16	|16 bits|	 
uint32	|32 bits|	 
uint64	|64 bits|	 

4. 浮点类型

类型|说明|表示字符
-|-|-
half|	 	|'e'|
single	|compatible: C float	|'f'
double	|compatible: C double	 
float_	|compatible: Python float	|'d'
longfloat	|compatible: C long float	|'g'
float16	|16 bits	| 
float32	|32 bits	| 
float64	|64 bits	 |
float96	|96 bits, platform?	 |
float128	|128 bits, platform?|

5. 复数类型

类型|说明|表示字符
-|-|-
csingle	| 	|'F'
complex_	|compatible: Python complex	'D'
clongfloat	| 	|'G'
complex64	|two 32-bit floats	 |
complex128	|two 64-bit floats	 |
complex192	|two 96-bit floats, platform?	 |
complex256	|two 128-bit floats, platform?	 |

6. 对象类型


类型|说明|表示字符
-|-|-
object_	|any Python object	|'O'


7. 字符类型

类型|说明|表示字符
-|-|-
bytes_	|compatible: Python bytes	|'S#'
unicode_	|compatible: Python unicode/str	|'U#'
void|	 	|'V#'


In [118]:
import numpy as np

# 使用内置类型构造
dt = np.dtype(np.float32)

# 直接使用内置类型
na = np.ndarray(shape=(3, 3), dtype=np.float32)

#### 泛型类型的对应内置类型

泛型类型|对应类型
-|-
number, inexact, floating	|float
complexfloating	|cfloat
integer, signedinteger	|int_
unsignedinteger	|uint
character	|string
generic, flexible	|void


In [119]:
import numpy as np

# 使用内置类型构造
dt = np.dtype(np.cfloat)

#### python内置内型的对应类型

python类型|对应类型
-|-
int	|int_
bool	|bool_
float	|float_
complex	|cfloat
bytes	|bytes_
str	|bytes_ (Python2) or unicode_ (Python3)
unicode	|unicode_
buffer	|void
(all others)	|object_

In [120]:
import numpy as np

# 使用内置类型构造
dt = np.dtype(int)

#### 使用已知的dtype类型

In [121]:
import numpy as np
na = np.ndarray(shape=(3, 3))

na2 = np.ndarray(shape=(3, 3), dtype=na.dtype)

#### 表示类型的单字符

- `< 小端字节序`
- `> 大端字节序`

In [122]:
import numpy as np
dt = np.dtype('b')  # byte, native byte order
dt = np.dtype('>H') # big-endian unsigned short
dt = np.dtype('<f') # little-endian single-precision float
dt = np.dtype('d')  # double-precision floating-point number

#### 指定长度的字符


符号|类型
-|-
'?'	|boolean
'b'	|(signed) byte
'B'	|unsigned byte
'i'	|(signed) integer
'u'	|unsigned integer
'f'	|floating-point
'c'	|complex-floating point
'm'	|timedelta
'M'	|datetime
'O'	|(Python) objects
'S', 'a'	|zero-terminated bytes (not recommended)
'U'	|Unicode string
'V'	|raw data (void)

In [123]:
import numpy as np

dt = np.dtype('i4')   # 32-bit signed integer
dt = np.dtype('f8')   # 64-bit floating-point number
dt = np.dtype('c16')  # 128-bit complex floating-point number
dt = np.dtype('a25')  # 25-length zero-terminated bytes
dt = np.dtype('U25')  # 25-character string

#### 逗号分隔的字段字符串

- 定义复合类型：多个字段

In [124]:
import numpy as np
dt = np.dtype("i4, (2,3)f8, f4")   # 表示三个字段  ，其中第二个字段表示形状为(2,3)的数组

#### 类型字符串

In [125]:
import numpy as np

# dt = np.dtype('uint32')   # 32-bit unsigned integer
# dt = np.dtype('Float64')  # 64-bit floating-point number
dt = np.dtype('uint32') 

# 上面字符串可以使用如下代码获取
# print(np.sctypeDict)

dt = np.dtype('string_') 

### 构造元素是结构的数组

#### 构造多字段元素的数组

In [126]:
import numpy as np

na = np.ndarray(shape=(3, 3),  dtype=np.dtype("i4, (2,2)i4, f8"))
print(na)

print('一个元素：',na[1,1])

[[(         0, [[-805306368, -311925863], [-805304326,         17]],  0.00000000e+000)
  (         0, [[         0,        109], [1936532091, 1684627303]],  1.80167974e+185)
  (1681351735, [[ 878784566,  960050790], [ 945894961,  929182771]],  5.24969644e-144)]
 [(1937056300, [[1634628197,  975332717], [1702065442, 1835101810]],  1.35617292e+248)
  ( 577662825, [[1697849914,  875640886], [ 875651888, 1697931572]],  1.45233191e-051)
  (1650745651, [[ 825700966,  740450659], [1735617826, 1887007839]],  6.48224638e+170)]
 [(1600484469, [[1970365810,  578057061], [1702240812, 1869181810]],  5.82381892e-144)
  (1633952300, [[ 975332724,  825242146], [ 875572537, 1412772141]],  4.08825530e-033)
  ( 876098606, [[1513239097, -310543070], [      2042,          0]], -1.07434484e+219)]]
一个元素： (577662825, [[1697849914,  875640886], [ 875651888, 1697931572]], 1.45233191e-51)


#### 指定数据大小(flexible_dtype, itemsize)

In [127]:
import numpy as np
dt = np.dtype(('U', 10)) 

na = np.ndarray(shape=(3, 3),  dtype=np.dtype(('U', 10)))
na[1,1]='abcdefghijklmn'
print(na)

[['' '' '']
 ['' 'abcdefghij' '']
 ['' '' '']]


3. 指定数组类型(fixed_dtype, shape)

In [128]:
import numpy as np
dt = np.dtype((np.int32, (2,2)))



na = np.ndarray(shape=(3, 3),  dtype=np.dtype((np.int32, (2,2))))
na[1,1]=np.array(
    [
        [1,2],
        [3,4]
    ])
print(na)

[[[[-805306368          0]
   [-805306368         16]]

  [[         0 -805306368]
   [1702240891 1869181810]]

  [[ 975332724  825242146]
   [ 875572537 1412772141]]]


 [[[1513108022 1931619362]
   [1769173861  975335023]]

  [[         1          2]
   [         3          4]]

  [[1835101810  574235237]
   [1735287161 1851877745]]]


 [[[1931622946 1970561396]
   [ 573317747 1600615277]]

  [[1680878896  828781362]
   [ 825307959  842217529]]

  [[1513109297    8224034]
   [    655469          0]]]]


4. 构造有字段名的类型
    - `[(field_name, field_dtype, field_shape), ...]`

In [129]:
import numpy as np

na = np.ndarray(shape=(3, 3),  dtype=np.dtype([('name', ('U', 10)),('age', 'i4')]))
na[1,1]['name']='Louis'
na[1,1]['age']=18
print(na)

[[('',  0) ('',  0) ('',  0)]
 [('',  0) ('Louis', 18) ('',  0)]
 [('',  0) ('',  0) ('',  0)]]


### 使用函数构造ndarray数组

#### 1-0构成的数组

- `numpy.empty(shape, dtype=float, order='C')`
- `numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')`
- `numpy.identity(n, dtype=None)`
- `numpy.zeros(shape, dtype=float, order='C')`
- `numpy.full(shape, fill_value, dtype=None, order='C')`

- `numpy.full_like(a, fill_value, dtype=None, order='K', subok=True)`

In [130]:
import numpy as np

na = np.empty(shape=(3, 3))   # 这个值不确定
print(na)

na = np.eye(N=3, M=3, k=1)   # k指定对角线的位置
print(na)

na = np.full(shape=(3,3), fill_value=1)   
print(na)

na = np.identity(3)    # 等价矩阵
print(na)

# ------------
na = np.full_like(na, fill_value=1)   
print(na)


[[ 0.00000000e+000  1.80167974e+185  5.24969644e-144]
 [ 1.35617292e+248  1.45233191e-051  6.48224638e+170]
 [ 5.82381892e-144  4.08825530e-033 -1.07434484e+219]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### 使用已知Python数组构造

- `numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)`
- `numpy.asmatrix(data, dtype=None)`

In [131]:
import numpy as np

na = np.array(
    [1,2
#         [1,2],
#         [3,4]
    ]
)

print(na.shape)
print(na)


na = np.asmatrix(
    [1,2
#         [1,2],
#         [3,4]
    ]
)

print(na.shape)
print(na)

(2,)
[1 2]
(1, 2)
[[1 2]]


#### 使用指定范围构造数组

- `numpy.arange([start, ]stop, [step, ]dtype=None)`
- `numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)` 
- `numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)`
- `numpy.meshgrid(*xi, **kwargs)`
- `numpy.mgrid`
- `numpy.ogrid`

In [132]:
import numpy as np

na = np.arange(1, 10, 1)
print(na)

na = np.linspace(1, 9, 3)
print(na)

# -----------网格
x = np.linspace(1, 10, 10)
y = np.linspace(-1, -10, 10)
print(x,y)

ms = np.meshgrid(x, y,indexing='xy')
print(ms)

[1 2 3 4 5 6 7 8 9]
[1. 5. 9.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] [ -1.  -2.  -3.  -4.  -5.  -6.  -7.  -8.  -9. -10.]
[array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]), array([[ -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.],
       [ -2.,  -2.,  -2.,  -2.,  -2.,  -2.,  -2.,  -2.,  -2.,  -2.],
       [ -3.,  -3.,  -3.,  -3.,  -3.,  -3.,  -3.,  -3.,  -3.,  -3.],
       [ -4.,  -4.,  -4.,  -4.,  -4.,  -4.,  -4.,  -4.,  -4.,  -4.],
      

In [133]:
import numpy as np

na = np.mgrid[-1:1:5j, 1:10:10j]
print(na)

na = np.ogrid[0:5:6j,0:5:6j]
print(na)

[[[-1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1. ]
  [-0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5 -0.5]
  [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
  [ 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5]
  [ 1.   1.   1.   1.   1.   1.   1.   1.   1.   1. ]]

 [[ 1.   2.   3.   4.   5.   6.   7.   8.   9.  10. ]
  [ 1.   2.   3.   4.   5.   6.   7.   8.   9.  10. ]
  [ 1.   2.   3.   4.   5.   6.   7.   8.   9.  10. ]
  [ 1.   2.   3.   4.   5.   6.   7.   8.   9.  10. ]
  [ 1.   2.   3.   4.   5.   6.   7.   8.   9.  10. ]]]
[array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.]]), array([[0., 1., 2., 3., 4., 5.]])]


#### 构造矩阵

- `numpy.diag(v, k=0)`  返回对角线
- `numpy.tri(N, M=None, k=0, dtype=<class 'float'>)`


In [134]:
import numpy as np

m = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9,10,11,12]
    ]
)

na = np.diag(m,k=1)  # k 是对角线的偏移位置
print(na)

na = np.tri(3,4, -1)   # k可以取正负，以对角线为准
print(na)

[ 2  7 12]
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 1. 0. 0.]]


#### 创建矩阵类型

- `numpy.mat(data, dtype=None)`

In [135]:
import numpy as np

m = np.mat(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9,10,11,12]
    ]
)
print(type(m))

<class 'numpy.matrixlib.defmatrix.matrix'>


### 使用第三方工具返回ndarray数组

#### 鸢尾花数组

- 在sklearn模块中可以加载鸢尾花

In [136]:
import sklearn.datasets

data,target = sklearn.datasets.load_iris(return_X_y=True)
print(type(data), type(target))


<class 'numpy.ndarray'> <class 'numpy.ndarray'>


#### 加载图像文件数组

In [137]:
import cv2

img=cv2.imread('huanqiu.png')
print(type(img))


<class 'numpy.ndarray'>


#### 使用matplotlib打开图像

In [138]:
import matplotlib.pyplot as plt

image = plt.imread('huanqiu.png')
print(type(image))

<class 'numpy.ndarray'>


#### 抓取摄像头图像数组

In [ ]:
#!/usr/bin/python
# coding = utf-8
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
import cv2
import sys

class MainWidget(QWidget):
    def __init__(self):
        super(MainWidget, self).__init__()
        self.timer = QTimer()
        # 窗体初始化
        screen = QApplication.desktop()
        screen_w = screen.width()
        screen_h = screen.height()
        self.setWindowFlags(
            Qt.CustomizeWindowHint |
            Qt.WindowMinimizeButtonHint |
            Qt.WindowCloseButtonHint
        )
        # self.setWindowState(Qt.WindowFullScreen)
        self.setGeometry(
            (screen_w - 800) / 2, (screen_h - 600) / 2,
            800, 600)
        # 显示视频图像
        self.lbl_qr = QLabel(self, text='<font size=20>视频采集中...</font>')
        self.lbl_qr.setAlignment(Qt.AlignCenter)
        self.lbl_qr.setGeometry((800 - 640)/2, (600 - 360)/2, 640, 360)
        self.show()

        self.dev = cv2.VideoCapture(0)

        self.timer.timeout.connect(self.capture_video)
        self.timer.start(100)

    def capture_video(self):
        status, img = self.dev.read()
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        image = QImage(img,   # 图像的子节数组(numpy.ndarray)
                       img.shape[1],   # 图像高度
                       img.shape[0],   # 图像宽度
                       img.shape[1] * 3,  # 每行的字节数
                       QImage.Format_RGB888)  # 图像的格式3个子节
        png1 = QPixmap(image)
        self.lbl_qr.setPixmap(png1)
        self.lbl_qr.setScaledContents(True)


app = QApplication(sys.argv)
ui_main = MainWidget()
sys.exit(app.exec())
